__Eri rypälelajikkeet - logistinen regressio__

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_excel('http://taanila.fi/wine.xlsx')
df.head()

Y     X1    X2    X3    X4   X5    X6    X7    X8    X9   X10   X11   X12  \
0  1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

    X13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [3]:
#Asetetaan feature-matriisi
X=df.drop('Y',axis=1)

#Asetetaan target (Y)
y=df['Y']

In [4]:
#Jaetaan malli opetus ja testidataan
from sklearn.model_selection import train_test_split
X_opetus, X_testi, y_opetus, y_testi = train_test_split(X,y,random_state=4)

In [5]:
#Tuodaan logistisen regression -malli ja sovitetaan data malliin
from sklearn.linear_model import LogisticRegression as LogR
malli=LogR()
malli.fit(X_opetus,y_opetus)

C:\Users\JoelM\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\JoelM\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [6]:
#Lasketaan mallin mukaiset ennusteet opetus- ja testidatalle
y_opetus_malli = malli.predict(X_opetus)
y_testi_malli = malli.predict(X_testi)

In [7]:
#Mallin hyvyys opetusdataan
from sklearn.metrics import accuracy_score
accuracy_score(y_opetus,y_opetus_malli)

0.9849624060150376

In [8]:
#Mallin hyvyys testidataan
accuracy_score(y_testi,y_testi_malli)

0.9333333333333333

In [9]:
#Confusion-matriisi opetusdatalle:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_opetus, y_opetus_malli))

[[42  2  0]
 [ 0 56  0]
 [ 0  0 33]]


In [10]:
#Confusion-matriisi testidatalle:

print(confusion_matrix(y_testi, y_testi_malli))

[[14  1  0]
 [ 1 13  1]
 [ 0  0 15]]


Mallin sopivuus on hyvä, mutta GaussianNB oli ehkä vielä parempi