__Logistinen regressio__

In [1]:
#Tuodaan kirjastot
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#Näytetään kuviot notebookissa heti koodin alla
%matplotlib inline

In [2]:
df=pd.read_excel('Aineisto_analyytikoille_lopullinen_2.xlsx')
df.head()

KAUPPAREKISTERINRO  Yrityksen_ikä_kk YHTIOMUOTO  P_TOIMIALAKOODI  \
0             002361              1390         OY            46210   
1             004317              1389         OY            58130   
2             006143              1388         OY            64200   
3             008087              1385         OY            68209   
4             008294              1383         OY            68209   

   P_Toimialan_maksuhäiriöriski  P_kiinnitysten_EUR  \
0                           4.7                 0.0   
1                           5.3                 0.0   
2                           4.5                 0.0   
3                           1.9                 0.0   
4                           1.9                 0.0   

   P_Positiiviset_Maksutavat_EUR  \
0                        1031568   
1                            221   
2                          23265   
3                              0   
4                           9391   

   P_Positiivisten_maksutapojen_toimittajien_LKM  \
0                                             14   
1                                              1   
2                                              4   
3                                              0   
4                                              1   

   P_Maksuviiveiden_yli8päivää_EUR  \
0                             3192   
1                                0   
2                                0   
3                                0   
4                                0   

   P_Maksuviiveiden_yli8päivää_Toimittajien_LKM  ...  P_Omavaraisuusaste  \
0                                             3  ...                26.4   
1                                             0  ...                60.1   
2                                             0  ...                60.6   
3                                             0  ...                68.7   
4                                             0  ...                95.9   

   P_KOKONAISPAAOMA_TUOTTO  P_QUICKRATIO  P_OMA_PAAOMA  \
0                      3.4           0.5      65052744   
1                     13.3           2.2       3619000   
2                     19.5           0.9     534200000   
3                    -10.7           2.5        213000   
4                     -4.7           1.2       1795000   

   P_MAKSUHAIRIOT_alle1Vuotta_vanhojen_KPL  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   P_MAKSUHAIRIOT_1_vuodesta_2_vuoteen_vanhojen_KPL  \
0                                                 0   
1                                                 0   
2                                                 0   
3                                                 0   
4                                                 0   

   P_MAKSUHAIRIOT_yli_2_vuotta_vanhojen_KPL  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   

   Yritystä_haettu_konkurssiin_velkojan_toimesta  Yrityssaneeraus  VASTE  
0                                              0                0      0  
1                                              0                0      0  
2                                              0                0      0  
3                                              0                0      0  
4                                              0                0      0  

[5 rows x 40 columns]

In [3]:
#Katsotaan yhtiömuotojen ja eri arvot
df['YHTIOMUOTO'].unique()

array(['OY', 'OK', 'KO', 'KY', 'AY'], dtype=object)

In [4]:
#Korvataan yhtiömuodot numeroilla 0-4
df['YHTIOMUOTO'] = df['YHTIOMUOTO'].map({'OY': 0, 'OK': 1, 'KO': 2, 'KY': 3, 'AY': 4})
df['YHTIOMUOTO'].unique()

array([0, 1, 2, 3, 4], dtype=int64)

In [5]:
#Tarkistetaan onko puuttuvia arvoja
df.dropna(how='all')
df.isnull().sum()

KAUPPAREKISTERINRO                                     0
Yrityksen_ikä_kk                                       0
YHTIOMUOTO                                             0
P_TOIMIALAKOODI                                        0
P_Toimialan_maksuhäiriöriski                           0
P_kiinnitysten_EUR                                     0
P_Positiiviset_Maksutavat_EUR                          0
P_Positiivisten_maksutapojen_toimittajien_LKM          0
P_Maksuviiveiden_yli8päivää_EUR                        0
P_Maksuviiveiden_yli8päivää_Toimittajien_LKM           0
P_Maksuviiveiden_keskiviive_päivissä                   0
P_Trattapohjaisten_maksuviiveiden_LKM                  0
P_Hallituksen_LKM                                      0
P_Varajäsenten_LKM                                     0
P_Vastuuhenkilöiden_LKM                                0
P_Häiriöllisiä_henkilöitä_hallituksessa_LKM            0
Varsinaisten_jäsenten_omat_häiriömerkinnät             0
Varsinaisten_jäsenten_konkurssi

In [6]:
df = df.fillna(0)

In [7]:
#Features matriisi
X = df.drop(['KAUPPAREKISTERINRO','VASTE'],axis=1)
#Target matriisi
y = df['VASTE']

In [8]:
#Jaetaan data opetus- ja testidataan
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, random_state=4)

In [9]:
#Tuodaan logistisen regression malli
from sklearn.linear_model import LogisticRegression as LogR

#Sovitetaan malli
malli = LogR()
malli.fit(X_train, y_train)

#Lasketaan mallin mukaiset ennusteet
y_train_malli = malli.predict(X_train)
y_test_malli = malli.predict(X_test)

C:\Users\JoelM\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\JoelM\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [10]:
#Katsotaan kuinka moni ennusteista osui oikeaan opetusdatassa
from sklearn.metrics import accuracy_score

accuracy_score(y_train, y_train_malli)

0.9385928905672769

In [11]:
#Katsotaan kuinka moni ennusteista osui oikeaan testidatassa
accuracy_score(y_test, y_test_malli)

0.9357301157350406

In [12]:
#Confusion-matriisi opetusdatalle:

from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_train, y_train_malli))

[[11433     2]
 [  746     0]]


In [13]:
#Confusion-matriisi testidatalle:
print(confusion_matrix(y_test,y_test_malli))

[[3800    0]
 [ 261    0]]


In [14]:
df.groupby('VASTE').count()

KAUPPAREKISTERINRO  Yrityksen_ikä_kk  YHTIOMUOTO  P_TOIMIALAKOODI  \
VASTE                                                                      
0                   15235             15235       15235            15235   
1                    1007              1007        1007             1007   

       P_Toimialan_maksuhäiriöriski  P_kiinnitysten_EUR  \
VASTE                                                     
0                             15235               15235   
1                              1007                1007   

       P_Positiiviset_Maksutavat_EUR  \
VASTE                                  
0                              15235   
1                               1007   

       P_Positiivisten_maksutapojen_toimittajien_LKM  \
VASTE                                                  
0                                              15235   
1                                               1007   

       P_Maksuviiveiden_yli8päivää_EUR  \
VASTE                                    
0                                15235   
1                                 1007   

       P_Maksuviiveiden_yli8päivää_Toimittajien_LKM  ...  P_TASE  \
VASTE                                                ...           
0                                             15235  ...   15235   
1                                              1007  ...    1007   

       P_Omavaraisuusaste  P_KOKONAISPAAOMA_TUOTTO  P_QUICKRATIO  \
VASTE                                                              
0                   15235                    15235         15235   
1                    1007                     1007          1007   

       P_OMA_PAAOMA  P_MAKSUHAIRIOT_alle1Vuotta_vanhojen_KPL  \
VASTE                                                          
0             15235                                    15235   
1              1007                                     1007   

       P_MAKSUHAIRIOT_1_vuodesta_2_vuoteen_vanhojen_KPL  \
VASTE                                                     
0                                                 15235   
1                                                  1007   

       P_MAKSUHAIRIOT_yli_2_vuotta_vanhojen_KPL  \
VASTE                                             
0                                         15235   
1                                          1007   

       Yritystä_haettu_konkurssiin_velkojan_toimesta  Yrityssaneeraus  
VASTE                                                                  
0                                              15235            15235  
1                                               1007             1007  

[2 rows x 39 columns]